notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python35" PYTHON_VERSION="3.5"
      PATH_TO_PYTHON="/opt/python/cp35-cp35m"
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python34" PYTHON_VERSION="3.4"
      PATH_TO_PYTHON="/opt/python/cp34-cp34m"
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE="Python27" PYTHON_VERSION="2.7"
      PATH_TO_PYTHON="/opt/python/cp27-cp27m"
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python35" PYTHON_VERSION="3.5"
      PATH_TO_PYTHON="/opt/python/cp35-cp35m" PRE_CMD=linux32
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python34" PYTHON_VERSION="3.4"
      PATH_TO_PYTHON="/opt/python/cp34-cp34m" PRE_CMD=linux32
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE="Python27" PYTHON_VERSION="2.7"
      PATH_TO_PYTHON="/opt/python/cp27-cp27m" PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -e TWINE_PASSWORD -e BUILD_TYPE -e PYTHON_VERSION -e PATH_TO_PYTHON
  -e TRAVIS_TAG -v `pwd`:/dcgp $DOCKER_IMAGE $PRE_CMD /dcgp/tools/install_travis.sh
env:
  global:
    secure: rutYylvpFA+MklZcuQo32452s7L4CMV/lzaF1ccrLvQ94DoAvCYWQm2v1b2Qw9eLXi5+f3TW7BmUDjxKfULpoWH/q2Q+/9W2roixziKoKmxmvtkNPWT4m4EPMEft2Y0eLxMu7arUnezcsv8j3fBEOQZxiTKQrt2EEn6FKSepax+4+ls6oE1VwdGMOAtAeReAqt/aBRwxl5+8P1QPs4B5Mc+7SPvqWaOOXr/3cFpQ10YFsp99L48lCUMnLf6ocbf55Bn9o7/bUTwezzQ3WRz11t5uwNiZDp4Nf76QpQ3zKhoM37fgQ2QlkEUL+BuCzwuPdmMgNInBSwUFnOjVL097l3Sb87lXO0mxS1vDZv1Xks8D9UOLiXb+WMHxyrDf2llGr+4zKzLZrjcJI6Ouz9UzGb81CDQOAsRwls4X1DLpq8ElQp+9bM7lgW3bWE4eB79wLMGcw7wVqqcbf8Th62Nbt2457jraogEYa1gFmoK7YhAS2fmEZK8GoS9uOvmfpQKykZzLb2VNOG8G+kRgovO/4i2rPQ0D1/RJC+8IFv6l5U6Y6mZzFUoFEk7chGY/BxholD3xoSEQpOVrjY95DZhLBEcEeCTAU0N7MBuirF/z+xEGD1JOGzNlKeHLR6v13Ztnv8ih3deO6mnE5nvLZmcqJN3UGRFK6/nryWKVEt2Wqi0=
